import './globals.css'
import { ChakraProviders } from './provider'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='ko'>
      <body suppressHydrationWarning={true}>
        <ChakraProviders>{children}</ChakraProviders>
      </body>
    </html>
  )
}
